esphome:
  name: xmas-master
  friendly_name: Xmas-Master

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

# Uncomment if LVGL isn't included in your ESPHome version
# external_components:
#   - source: github://clydebarrow/esphome@lvgl
#     components: [ lvgl ]
#     refresh: 10min

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Cyd-Ha-Dashboard"
    password: !secret hotspot_password

captive_portal:
